import * as ko from 'knockout';
import 'isomorphic-fetch';
import { SampleDataService } from '../../_autogenerated/SampleDataService';
import { DataService } from '../../_autogenerated/DataService';

interface WeatherForecast {
    dateFormatted: string;
    temperatureC: number;
    temperatureF: number;
    summary: string;
}

class FetchDataViewModel {
    public forecasts = ko.observableArray<WeatherForecast>();

    constructor() {
        // this.getData();
        this.getApiData();
    }

    private getData = async () => {
        var test = await SampleDataService.weatherForecasts();
    }
    private logout = async () => {
        await SampleDataService.logout();
        window.location.href = "/";
    }

    private getApiData = async () => {
        const data = await DataService.getDataAsync();
        console.log(data);
    }
}

export default { viewModel: FetchDataViewModel, template: require('./fetch-data.html') };
