import * as ko from 'knockout';
import 'isomorphic-fetch';
import { DataService } from '../../_autogenerated/DataService';
import { UserDto } from '../../_autogenerated/UserDto';
import { SpaService } from '../../_autogenerated/SpaApiService';

declare var User: UserDto;

class HomePageViewModel {
    private user: UserDto = User;

    constructor() {
        // this.getData();
        //this.getApiData();
        // this.getPolicyProtectedDataAsync();
        //this.getCustomRequirementProtectedDataAsync();
    }

    private getClientSpaProtectedApiDataAsync = async () => {
        var test = await SpaService.getClientSpaProtectedApiDataAsync();
    }
    private getApiData = async () => {
        const data = await DataService.getDataAsync();
        console.log(data);
    }
    private getPolicyProtectedDataAsync = async () => {
        const data = await DataService.getPolicyProtectedDataAsync();
        console.log(data);
    }
    private getCustomRequirementProtectedDataAsync = async () => {
        const data = await DataService.getCustomRequirementProtectedDataAsync(5);
        console.log(data);
    }
}



export default { viewModel: HomePageViewModel, template: require('./home-page.html') };
